### PR TITLE
Fixes RemovedInDjango110Warning

### PR DESCRIPTION
**Pull request by sbywater**

### CODE REVIEW

**Comment by nigma** [comment]
Thanks. I'm working on a new release in #34 / develop that includes this change to template context handling.

**Comment by jerzyk** [comment]
@nigma can I suggest to release *existing* version with those changes? what I can see, new version is using totally different rendering engine and in most of the cases will require major changes to dependencies and templates. It will be nice to have *now* a backwards compatible version of the library working with current django without need to rebuild everything...

**Comment by jerzyk** [comment]
one more comment, this PR is not complete - function `render_to_pdf_response` is still not fixed

**Comment by nigma** [comment]
@jerzyk good suggestion.

This issue should be resolved in the releases published to PyPI today:
- 0.1.1 - last build supporting xhtml2pdf
- 0.2.0-dev1 - developer preview using WeasyPrint

See https://github.com/nigma/django-easy-pdf/releases.

**Pull request closed without merging**
